description = "Web Servlet Library following JSR 154, JSR 315 (Core)"
name = "servletada"
version = "1.5.0"
licenses = ["Apache 2.0"]
maintainers = ["Stephane.Carrez@gmail.com"]
maintainers-logins = ["stcarrez"]
project-files = [".alire/servletada.gpr"]
tags = ["servlet", "rest", "http"]
website = "https://gitlab.com/stcarrez/ada-servlet"

[[actions]]
type = "post-fetch"
command = ["rm", "-f", "config.gpr"]

[[depends-on]]
security = "^1.2.2"
elada = "^1.8.0"
utilada = "^2.1.0"

[gpr-externals]
BUILD = ["distrib", "debug", "optimize", "profile", "coverage"]
SERVLET_LIBRARY_TYPE = ["relocatable", "static", "static-pic"]
